export const locales = ["zh", "en", "ja", "ko", "fr", "de"] as const;
export type Locale = (typeof locales)[number];

export const languageInfo: Record<Locale, { label: string; htmlLang: string }> = {
  zh: { label: "中文", htmlLang: "zh-CN" },
  en: { label: "English (US)", htmlLang: "en-US" },
  ja: { label: "日本語", htmlLang: "ja-JP" },
  ko: { label: "한국어", htmlLang: "ko-KR" },
  fr: { label: "Français", htmlLang: "fr-FR" },
  de: { label: "Deutsch", htmlLang: "de-DE" },
};

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

export function localeHref(locale: Locale, page = ""): string {
  const suffix = page ? `/${page}` : "";
  return locale === "zh" ? suffix || "/" : `/${locale}${suffix}`;
}

export const copy = {
  zh: {
    common: { install: "安装", privacy: "隐私", support: "支持", start: "立即开始", product: "产品", help: "帮助", legal: "法律", installGuide: "安装指南", how: "工作方式", techSupport: "技术支持", contact: "联系我们", privacyPolicy: "隐私政策", footer: "屏幕到相机的本地文件传输。", footerNote: "Made for files that should stay close.", language: "语言" },
    home: { eyebrow: "屏幕到相机 · 无需云端", h1: "让文件，", h2: "从屏幕跃入手机。", lede: "QRBeam 把小文件编码成动态二维码。电脑负责播放，iPhone 负责扫描——不需要登录、数据线或云盘。", learn: "了解工作方式", facts: ["不上传文件", "CRC32 + SHA-256 校验", "最大 5 MiB"], ticker: ["离线优先", "仅限本地", "校验传输", "屏幕到相机", "无需账户"], howKicker: "HOW IT WORKS", howTitle: "三步，隔空传过去", howBody: "QRBeam 在电脑本地启动播放器。每一帧都带有校验信息，手机收齐后再恢复原文件。", steps: [["安装命令行工具", "任选 Python 或 Node.js，一条命令完成安装。"], ["播放你的文件", "运行 qrbeam send FILE，浏览器自动打开动态二维码。"], ["用 iPhone 扫描", "QRBeam 收齐、校验并保存文件，然后可直接分享。"]], installKicker: "INSTALL IN SECONDS", installTitle: "选你熟悉的方式", installBody: "Python 与 Node.js 发送端使用同一种 QRB1 协议，接收体验完全一致。", installLink: "查看完整安装指南", comment1: "# 需要 Python 3.10+", comment2: "# 发送一个文件", status: "播放器将在 127.0.0.1 自动打开", trustKicker: "PRIVATE BY DESIGN", trustTitle: "你的文件，没有绕路。", trustBody: "文件内容和二维码帧都留在你的设备上。QRBeam 不创建账户，不上传所选文件，也不使用广告追踪。", trustLink: "阅读隐私政策", supportKicker: "NEED A HAND?", supportTitle: "卡住了，我们一起解决。", supportButton: "前往技术支持" },
    install: { eyebrow: "INSTALL", title: "两种语言，一种简单体验。", description: "选择电脑上已有的运行环境。Python 与 Node.js 版本都来自官方包仓库，并生成完全相同的 QRB1 动态二维码。", pyReq: "需要 Python 3.10 或更高版本", nodeReq: "需要 Node.js 20 或更高版本", recommended: "推荐", install: "安装 QRBeam", globalInstall: "全局安装 QRBeam", send: "发送文件", pypi: "在 PyPI 查看软件包", npm: "在 npm 查看软件包", usage: "开始第一次传输", usageBody: "命令运行后，QRBeam 会在浏览器中打开本地播放器。把 iPhone 后置相机对准屏幕即可。", steps: [["选择文件", "文件需不超过 5 MiB。"], ["运行命令", "qrbeam send FILE"], ["保持画面清晰", "浏览器全屏、提高亮度，手机稳定对准。"], ["等待校验完成", "收齐后由 SHA-256 校验文件。"]], options: "常用参数", optionText: ["默认，6 fps，更适合手持扫描", "10 fps，适合固定手机与明亮屏幕", "更改本地播放器端口", "不自动打开浏览器"] },
    privacy: { eyebrow: "PRIVACY", title: "隐私不是设置项，是默认值。", description: "QRBeam 的核心设计很简单：传输发生在你眼前，也留在你的设备上。最后更新：2026 年 8 月 9 日。", summary: "简要说明", bullets: ["不创建账户", "不上传所选文件", "不收集二维码内容", "不投放广告或跨应用追踪"], sections: [["适用范围", "本政策适用于 QRBeam iOS 应用、Python / Node.js 命令行发送端，以及本官网。使用第三方软件包仓库、Apple App Store 或外部链接时，对应服务商的隐私政策也可能适用。"], ["文件与二维码", "你选择发送或接收的文件在设备本地处理。电脑发送端仅在 127.0.0.1 启动播放器，不会把文件或二维码帧上传到 QRBeam 服务器。接收端会在本机组装文件，并使用 CRC32 与 SHA-256 检查完整性。"], ["相机", "iOS 应用请求相机权限，只用于扫描 QRBeam 动态二维码。QRBeam 不会把相机画面上传到服务器，也不会将相机画面用于身份识别、广告或分析。"], ["本地数据", "应用可能在设备上保存执行免费版限制所需的每日发送次数、设置和会员状态。已接收文件仅在你选择保存或分享时写入设备；删除应用或文件后，QRBeam 无法为你恢复。"], ["订阅与付款", "订阅购买和恢复由 Apple StoreKit 处理。QRBeam 会读取提供会员权益所需的订阅状态，但不会取得或保存你的完整银行卡信息。付款数据由 Apple 按其政策处理。"], ["官网数据", "官网当前不提供账户、广告、行为分析或营销 Cookie。网站托管服务商可能为安全、故障排查和稳定运行处理标准请求信息，例如 IP 地址、浏览器类型与访问时间。"], ["安全边界", "QRBeam 会验证文件完整性，但当前传输协议不提供端到端加密。请只传输你有权处理的文件，并遵守所在组织的安全与数据管理要求。"], ["联系我们", "如果你对隐私政策有疑问，请发送邮件至 lsl8315@163.com。政策更新后，我们会在本页面修改“最后更新”日期。"]] },
    support: { eyebrow: "SUPPORT", title: "把问题留给我们，把文件带走。", description: "先看看常见解决办法；如果仍然卡住，可以直接通过邮件联系我们。", email: "邮件支持", emailHint: "适合账户、订阅或不便公开的问题", selfHelp: "自助排查", faqTitle: "常见问题", faqHint: "快速解决安装、端口和扫描问题", faqIntro: "QRBeam 不需要网络传输文件，但首次安装软件包仍需要网络连接。", faqs: [["找不到 qrbeam 命令", "关闭并重新打开终端。Python 用户可运行 python3 -m pip show qrbeam，Node.js 用户可运行 npm list --global qrbeam 检查安装位置。"], ["浏览器没有自动打开", "复制终端显示的本地地址到浏览器，通常是 http://127.0.0.1:8765。也可去掉 --no-open 后重新运行。"], ["端口已被占用", "指定另一个端口，例如 qrbeam send FILE --port 8766。播放器仍然只监听本机。"], ["扫描速度慢或识别不稳", "先使用默认 safe 模式。将浏览器全屏、提高屏幕亮度，避免反光，并让 iPhone 与屏幕保持稳定。"], ["传输一直没有完成", "动态二维码会循环播放，缺失帧会在下一轮补齐。保持应用在前台；如果进度长时间不变，重新开始并缩短扫描距离。"], ["文件无法发送", "确认文件存在且不超过 5 MiB。免费版在 iPhone 内还可能受每日次数与单文件 1 MiB 限制。"]], report: "让问题更快被定位", reportBody: "联系我们时，请附上这些信息。不要发送你正在传输的文件本身，除非你确认可以公开分享。", reportItems: ["QRBeam 版本（运行 qrbeam --version）", "电脑系统与 Python / Node.js 版本", "iPhone 型号与 iOS 版本", "完整错误文字或问题出现的步骤"] },
  },
  en: {
    common: { install: "Install", privacy: "Privacy", support: "Support", start: "Get started", product: "Product", help: "Help", legal: "Legal", installGuide: "Install guide", how: "How it works", techSupport: "Technical support", contact: "Contact", privacyPolicy: "Privacy policy", footer: "Local file transfer from screen to camera.", footerNote: "Made for files that should stay close.", language: "Language" },
    home: { eyebrow: "SCREEN TO CAMERA · NO CLOUD", h1: "Let your files", h2: "leap into your phone.", lede: "QRBeam turns small files into animated QR codes. Your computer plays them and your iPhone scans them—no account, cable, or cloud drive required.", learn: "See how it works", facts: ["No file uploads", "CRC32 + SHA-256 verification", "Up to 5 MiB"], ticker: ["OFFLINE FIRST", "LOCAL ONLY", "VERIFIED TRANSFER", "SCREEN TO CAMERA", "NO ACCOUNT"], howKicker: "HOW IT WORKS", howTitle: "Across the air in three steps", howBody: "QRBeam starts a player locally on your computer. Every frame includes verification data, and the phone restores the file only after receiving it.", steps: [["Install the CLI", "Choose Python or Node.js and install with one command."], ["Play your file", "Run qrbeam send FILE and the animated QR opens in your browser."], ["Scan with iPhone", "QRBeam collects, verifies, saves, and lets you share the file."]], installKicker: "INSTALL IN SECONDS", installTitle: "Use the runtime you know", installBody: "The Python and Node.js senders use the same QRB1 protocol and provide the same receiving experience.", installLink: "View the full install guide", comment1: "# Requires Python 3.10+", comment2: "# Send a file", status: "The player opens locally at 127.0.0.1", trustKicker: "PRIVATE BY DESIGN", trustTitle: "Your file takes no detour.", trustBody: "File contents and QR frames stay on your devices. QRBeam creates no account, uploads no selected files, and uses no ad tracking.", trustLink: "Read the privacy policy", supportKicker: "NEED A HAND?", supportTitle: "Stuck? Let’s solve it together.", supportButton: "Get technical support" },
    install: { eyebrow: "INSTALL", title: "Two runtimes. One simple experience.", description: "Choose the runtime already on your computer. Both official packages generate the same QRB1 animated QR stream.", pyReq: "Requires Python 3.10 or later", nodeReq: "Requires Node.js 20 or later", recommended: "Recommended", install: "Install QRBeam", globalInstall: "Install QRBeam globally", send: "Send a file", pypi: "View package on PyPI", npm: "View package on npm", usage: "Make your first transfer", usageBody: "QRBeam opens a local player in your browser. Point your iPhone’s rear camera at the screen.", steps: [["Choose a file", "Files must be 5 MiB or smaller."], ["Run the command", "qrbeam send FILE"], ["Keep the image clear", "Use full screen, raise brightness, and hold the phone steady."], ["Wait for verification", "SHA-256 verifies the file when complete."]], options: "Common options", optionText: ["Default 6 fps mode for handheld scanning", "10 fps for a fixed phone and bright screen", "Change the local player port", "Do not open the browser automatically"] },
    privacy: { eyebrow: "PRIVACY", title: "Privacy is the default, not a setting.", description: "QRBeam is built around one idea: the transfer happens in front of you and stays on your devices. Last updated August 9, 2026.", summary: "At a glance", bullets: ["No account", "No selected-file uploads", "No QR content collection", "No ads or cross-app tracking"], sections: [["Scope", "This policy covers the QRBeam iOS app, Python and Node.js command-line senders, and this website. Third-party package repositories, the Apple App Store, and external links may apply their own policies."], ["Files and QR codes", "Selected files are processed locally. The computer sender starts its player only on 127.0.0.1 and does not upload files or QR frames to a QRBeam server. The receiver assembles files on-device and verifies integrity with CRC32 and SHA-256."], ["Camera", "The iOS app requests camera access only to scan QRBeam animated codes. QRBeam does not upload camera footage or use it for identification, advertising, or analytics."], ["Local data", "The app may store daily free-send counts, settings, and membership status on-device. Received files are written only when you save or share them. QRBeam cannot recover files after you delete them or the app."], ["Subscriptions", "Apple StoreKit handles purchases and restoration. QRBeam reads the subscription status needed to provide benefits but does not receive or store full card details. Apple processes payment data under its own policy."], ["Website data", "This site currently has no accounts, advertising, behavior analytics, or marketing cookies. The hosting provider may process standard request information such as IP address, browser type, and access time for security and reliability."], ["Security boundary", "QRBeam verifies file integrity, but the current protocol does not provide end-to-end encryption. Transfer only files you are authorized to handle and follow your organization’s security requirements."], ["Contact", "For privacy questions, email lsl8315@163.com. We will revise the last-updated date when this policy changes."]] },
    support: { eyebrow: "SUPPORT", title: "Leave the problem with us. Take the file with you.", description: "Try these common fixes first. If you are still stuck, contact us by email.", email: "Email support", emailHint: "Best for account, subscription, or private questions", selfHelp: "Self-service", faqTitle: "Common questions", faqHint: "Quick fixes for installation, ports, and scanning", faqIntro: "QRBeam transfers files offline, but the initial package installation still requires internet access.", faqs: [["The qrbeam command is missing", "Reopen your terminal. Python users can run python3 -m pip show qrbeam; Node.js users can run npm list --global qrbeam to check the installation."], ["The browser did not open", "Open the local address shown in the terminal, usually http://127.0.0.1:8765. You can also rerun without --no-open."], ["The port is already in use", "Choose another port, for example qrbeam send FILE --port 8766. The player still listens locally only."], ["Scanning is slow or unstable", "Use the default safe profile, enter full screen, raise display brightness, avoid glare, and hold the phone steady."], ["The transfer never completes", "The stream loops so missing frames can arrive on the next pass. Keep the app in front; restart and move closer if progress remains stuck."], ["A file cannot be sent", "Make sure it exists and is no larger than 5 MiB. The free iPhone tier may also limit files to 1 MiB and one transfer per day."]], report: "Help us locate the issue faster", reportBody: "Include these details when you contact us. Do not send the file itself unless you are authorized to share it.", reportItems: ["QRBeam version (run qrbeam --version)", "Computer OS and Python or Node.js version", "iPhone model and iOS version", "Exact error text or reproduction steps"] },
  },
  ja: {
    common: { install: "インストール", privacy: "プライバシー", support: "サポート", start: "始める", product: "製品", help: "ヘルプ", legal: "法的情報", installGuide: "インストールガイド", how: "仕組み", techSupport: "技術サポート", contact: "お問い合わせ", privacyPolicy: "プライバシーポリシー", footer: "画面からカメラへ、ローカルでファイル転送。", footerNote: "大切なファイルを、身近なままに。", language: "言語" },
    home: { eyebrow: "画面からカメラへ · クラウド不要", h1: "ファイルを、", h2: "画面からスマホへ。", lede: "QRBeam は小さなファイルをアニメーション QR コードに変換します。パソコンで再生し、iPhone でスキャン。アカウント、ケーブル、クラウドは不要です。", learn: "仕組みを見る", facts: ["ファイルをアップロードしない", "CRC32 + SHA-256 検証", "最大 5 MiB"], ticker: ["オフライン優先", "ローカルのみ", "検証付き転送", "画面からカメラへ", "アカウント不要"], howKicker: "HOW IT WORKS", howTitle: "3 ステップで転送", howBody: "QRBeam はパソコン上でローカルプレーヤーを起動します。各フレームを検証し、スマホが受信後にファイルを復元します。", steps: [["CLI をインストール", "Python または Node.js を選び、1 コマンドでインストール。"], ["ファイルを再生", "qrbeam send FILE を実行すると、ブラウザに QR が表示されます。"], ["iPhone でスキャン", "QRBeam が受信、検証、保存し、そのまま共有できます。"]], installKicker: "INSTALL IN SECONDS", installTitle: "使い慣れた方法を選択", installBody: "Python と Node.js は同じ QRB1 プロトコルを使い、受信体験も同じです。", installLink: "詳しいインストールガイド", comment1: "# Python 3.10+ が必要", comment2: "# ファイルを送信", status: "127.0.0.1 でローカルプレーヤーが開きます", trustKicker: "PRIVATE BY DESIGN", trustTitle: "ファイルは寄り道しません。", trustBody: "ファイルと QR フレームは端末内に留まります。アカウント作成、選択ファイルのアップロード、広告追跡はありません。", trustLink: "プライバシーポリシー", supportKicker: "NEED A HAND?", supportTitle: "困ったときは、一緒に解決。", supportButton: "技術サポートへ" },
    install: { eyebrow: "INSTALL", title: "2 つの環境、同じシンプルさ。", description: "パソコンにある環境を選択してください。どちらも同じ QRB1 アニメーション QR を生成します。", pyReq: "Python 3.10 以降", nodeReq: "Node.js 20 以降", recommended: "おすすめ", install: "QRBeam をインストール", globalInstall: "QRBeam をグローバルにインストール", send: "ファイルを送信", pypi: "PyPI で見る", npm: "npm で見る", usage: "最初の転送", usageBody: "ブラウザにローカルプレーヤーが開きます。iPhone の背面カメラを画面に向けてください。", steps: [["ファイルを選択", "5 MiB 以下のファイルに対応。"], ["コマンドを実行", "qrbeam send FILE"], ["画面を鮮明に", "全画面と高輝度にし、スマホを固定。"], ["検証を待つ", "完了時に SHA-256 で検証。"]], options: "主なオプション", optionText: ["標準の 6 fps。手持ちスキャン向け", "固定したスマホと明るい画面向けの 10 fps", "ローカルポートを変更", "ブラウザを自動で開かない"] },
    privacy: { eyebrow: "PRIVACY", title: "プライバシーは初期設定です。", description: "転送は目の前で行われ、端末内に留まります。最終更新日：2026年8月9日。", summary: "概要", bullets: ["アカウント不要", "ファイルをアップロードしない", "QR 内容を収集しない", "広告・追跡なし"], sections: [["適用範囲", "本ポリシーは QRBeam iOS アプリ、Python / Node.js CLI、本サイトに適用されます。外部サービスには各社のポリシーが適用される場合があります。"], ["ファイルと QR", "ファイルは端末内で処理されます。送信側は 127.0.0.1 のみで再生し、QRBeam サーバーへアップロードしません。受信側は CRC32 と SHA-256 で検証します。"], ["カメラ", "カメラはアニメーション QR の読み取りにのみ使用します。映像のアップロード、識別、広告、分析には使用しません。"], ["ローカルデータ", "無料送信回数、設定、会員状態を端末に保存する場合があります。受信ファイルは保存または共有を選んだ場合のみ書き込まれます。"], ["サブスクリプション", "購入と復元は Apple StoreKit が処理します。QRBeam は特典に必要な状態のみ読み取り、カード情報は取得・保存しません。"], ["サイトデータ", "本サイトにはアカウント、広告、行動分析、マーケティング Cookie はありません。ホスティング事業者が安全運用のため標準的なアクセス情報を処理する場合があります。"], ["セキュリティ範囲", "完全性は検証しますが、現在のプロトコルはエンドツーエンド暗号化を提供しません。権限のあるファイルだけを転送してください。"], ["お問い合わせ", "プライバシーに関するご質問は lsl8315@163.com までお送りください。変更時には更新日を改定します。"]] },
    support: { eyebrow: "SUPPORT", title: "問題は私たちに。ファイルはあなたの手元に。", description: "まず一般的な解決方法をお試しください。解決しない場合はメールでお問い合わせください。", email: "メールサポート", emailHint: "アカウント、購読、非公開のご相談に", selfHelp: "セルフヘルプ", faqTitle: "よくある質問", faqHint: "インストール、ポート、スキャンを解決", faqIntro: "転送はオフラインですが、初回のパッケージインストールにはインターネットが必要です。", faqs: [["qrbeam コマンドが見つからない", "ターミナルを開き直してください。Python は python3 -m pip show qrbeam、Node.js は npm list --global qrbeam で確認できます。"], ["ブラウザが開かない", "ターミナルに表示されたローカル URL（通常 http://127.0.0.1:8765）を開いてください。"], ["ポートが使用中", "qrbeam send FILE --port 8766 のように別のポートを指定してください。"], ["スキャンが遅い・不安定", "safe モード、全画面、高輝度を使い、反射を避けてスマホを固定してください。"], ["転送が完了しない", "ストリームは繰り返されます。アプリを前面に保ち、進まない場合は距離を縮めて再開してください。"], ["ファイルを送信できない", "ファイルが存在し、5 MiB 以下か確認してください。無料版には 1 MiB と 1 日 1 回の制限があります。"]], report: "問題を早く特定するために", reportBody: "お問い合わせには以下を添えてください。許可がない限り、ファイル自体は送らないでください。", reportItems: ["QRBeam バージョン（qrbeam --version）", "OS と Python / Node.js バージョン", "iPhone と iOS のバージョン", "エラー全文または再現手順"] },
  },
  ko: {
    common: { install: "설치", privacy: "개인정보", support: "지원", start: "시작하기", product: "제품", help: "도움말", legal: "법적 고지", installGuide: "설치 가이드", how: "작동 방식", techSupport: "기술 지원", contact: "문의", privacyPolicy: "개인정보 처리방침", footer: "화면에서 카메라로 전송하는 로컬 파일 전송.", footerNote: "파일을 가까운 곳에 그대로.", language: "언어" },
    home: { eyebrow: "화면에서 카메라로 · 클라우드 불필요", h1: "파일을", h2: "화면에서 휴대폰으로.", lede: "QRBeam은 작은 파일을 움직이는 QR 코드로 바꿉니다. 컴퓨터에서 재생하고 iPhone으로 스캔하세요. 계정, 케이블, 클라우드가 필요 없습니다.", learn: "작동 방식 보기", facts: ["파일 업로드 없음", "CRC32 + SHA-256 검증", "최대 5 MiB"], ticker: ["오프라인 우선", "로컬 전용", "검증된 전송", "화면에서 카메라로", "계정 불필요"], howKicker: "HOW IT WORKS", howTitle: "세 단계로 무선 전송", howBody: "QRBeam은 컴퓨터에서 로컬 플레이어를 실행합니다. 각 프레임을 확인하고 휴대폰이 모두 받은 뒤 파일을 복원합니다.", steps: [["CLI 설치", "Python 또는 Node.js를 선택해 한 줄로 설치하세요."], ["파일 재생", "qrbeam send FILE을 실행하면 브라우저에 QR이 열립니다."], ["iPhone으로 스캔", "QRBeam이 수신, 검증, 저장하고 바로 공유합니다."]], installKicker: "INSTALL IN SECONDS", installTitle: "익숙한 방식을 선택하세요", installBody: "Python과 Node.js 전송기는 같은 QRB1 프로토콜과 동일한 수신 경험을 제공합니다.", installLink: "전체 설치 가이드", comment1: "# Python 3.10+ 필요", comment2: "# 파일 보내기", status: "127.0.0.1에서 로컬 플레이어가 열립니다", trustKicker: "PRIVATE BY DESIGN", trustTitle: "파일은 우회하지 않습니다.", trustBody: "파일 내용과 QR 프레임은 기기에 남습니다. 계정 생성, 선택 파일 업로드, 광고 추적이 없습니다.", trustLink: "개인정보 처리방침", supportKicker: "NEED A HAND?", supportTitle: "막히셨나요? 함께 해결해요.", supportButton: "기술 지원" },
    install: { eyebrow: "INSTALL", title: "두 런타임, 하나의 간단한 경험.", description: "컴퓨터에 있는 환경을 선택하세요. 두 공식 패키지는 같은 QRB1 QR 스트림을 만듭니다.", pyReq: "Python 3.10 이상", nodeReq: "Node.js 20 이상", recommended: "추천", install: "QRBeam 설치", globalInstall: "QRBeam 전역 설치", send: "파일 보내기", pypi: "PyPI에서 보기", npm: "npm에서 보기", usage: "첫 전송 시작", usageBody: "브라우저에 로컬 플레이어가 열립니다. iPhone 후면 카메라를 화면에 맞추세요.", steps: [["파일 선택", "5 MiB 이하 파일을 사용하세요."], ["명령 실행", "qrbeam send FILE"], ["화면을 선명하게", "전체 화면과 높은 밝기를 사용하고 휴대폰을 고정하세요."], ["검증 대기", "완료 후 SHA-256으로 검증합니다."]], options: "주요 옵션", optionText: ["기본 6 fps, 손으로 들고 스캔할 때", "고정된 휴대폰과 밝은 화면용 10 fps", "로컬 플레이어 포트 변경", "브라우저를 자동으로 열지 않음"] },
    privacy: { eyebrow: "PRIVACY", title: "개인정보 보호는 기본값입니다.", description: "전송은 눈앞에서 이루어지고 기기에 남습니다. 최종 업데이트: 2026년 8월 9일.", summary: "요약", bullets: ["계정 없음", "선택 파일 업로드 없음", "QR 내용 수집 없음", "광고 및 교차 앱 추적 없음"], sections: [["적용 범위", "이 정책은 QRBeam iOS 앱, Python / Node.js CLI와 이 웹사이트에 적용됩니다. 외부 서비스에는 자체 정책이 적용될 수 있습니다."], ["파일과 QR", "파일은 로컬에서 처리됩니다. 전송기는 127.0.0.1에서만 재생하며 QRBeam 서버에 업로드하지 않습니다. 수신기는 CRC32와 SHA-256으로 검증합니다."], ["카메라", "카메라는 움직이는 QR 스캔에만 사용됩니다. 영상은 업로드되지 않으며 식별, 광고, 분석에 사용되지 않습니다."], ["로컬 데이터", "무료 전송 횟수, 설정, 멤버십 상태를 기기에 저장할 수 있습니다. 받은 파일은 저장 또는 공유할 때만 기록됩니다."], ["구독", "구매와 복원은 Apple StoreKit이 처리합니다. QRBeam은 혜택 제공에 필요한 구독 상태만 읽고 전체 카드 정보를 저장하지 않습니다."], ["웹사이트 데이터", "이 사이트에는 계정, 광고, 행동 분석, 마케팅 쿠키가 없습니다. 호스팅 제공자가 보안과 안정성을 위해 표준 요청 정보를 처리할 수 있습니다."], ["보안 범위", "파일 무결성은 검증하지만 현재 프로토콜은 종단 간 암호화를 제공하지 않습니다. 권한이 있는 파일만 전송하세요."], ["문의", "개인정보 관련 문의는 lsl8315@163.com으로 보내주세요. 정책 변경 시 업데이트 날짜를 수정합니다."]] },
    support: { eyebrow: "SUPPORT", title: "문제는 저희에게, 파일은 당신에게.", description: "먼저 자주 쓰는 해결 방법을 확인하세요. 해결되지 않으면 이메일로 문의해 주세요.", email: "이메일 지원", emailHint: "계정, 구독 또는 비공개 문의에 적합", selfHelp: "직접 해결", faqTitle: "자주 묻는 질문", faqHint: "설치, 포트, 스캔 문제 빠르게 해결", faqIntro: "파일 전송은 오프라인이지만 최초 패키지 설치에는 인터넷이 필요합니다.", faqs: [["qrbeam 명령을 찾을 수 없음", "터미널을 다시 여세요. Python은 python3 -m pip show qrbeam, Node.js는 npm list --global qrbeam으로 확인하세요."], ["브라우저가 열리지 않음", "터미널에 표시된 로컬 주소(보통 http://127.0.0.1:8765)를 여세요."], ["포트가 사용 중", "qrbeam send FILE --port 8766처럼 다른 포트를 지정하세요."], ["스캔이 느리거나 불안정", "safe 모드, 전체 화면, 높은 밝기를 사용하고 반사를 피하며 휴대폰을 고정하세요."], ["전송이 끝나지 않음", "스트림은 반복됩니다. 앱을 전면에 두고 멈추면 더 가까이에서 다시 시작하세요."], ["파일을 보낼 수 없음", "파일이 존재하고 5 MiB 이하인지 확인하세요. 무료 버전은 1 MiB 및 하루 1회 제한이 있을 수 있습니다."]], report: "더 빠른 문제 확인", reportBody: "문의 시 아래 정보를 보내주세요. 공개 권한이 없다면 파일 자체는 보내지 마세요.", reportItems: ["QRBeam 버전(qrbeam --version)", "컴퓨터 OS와 Python / Node.js 버전", "iPhone 모델과 iOS 버전", "전체 오류 문구 또는 재현 단계"] },
  },
  fr: {
    common: { install: "Installer", privacy: "Confidentialité", support: "Assistance", start: "Commencer", product: "Produit", help: "Aide", legal: "Mentions légales", installGuide: "Guide d’installation", how: "Fonctionnement", techSupport: "Assistance technique", contact: "Contact", privacyPolicy: "Politique de confidentialité", footer: "Transfert local de fichiers, de l’écran à la caméra.", footerNote: "Pour les fichiers qui doivent rester proches.", language: "Langue" },
    home: { eyebrow: "DE L’ÉCRAN À LA CAMÉRA · SANS CLOUD", h1: "Faites passer vos fichiers", h2: "de l’écran au téléphone.", lede: "QRBeam transforme les petits fichiers en QR codes animés. L’ordinateur les affiche, l’iPhone les scanne — sans compte, câble ni cloud.", learn: "Voir le fonctionnement", facts: ["Aucun fichier téléversé", "Vérification CRC32 + SHA-256", "Jusqu’à 5 Mio"], ticker: ["HORS LIGNE", "LOCAL UNIQUEMENT", "TRANSFERT VÉRIFIÉ", "ÉCRAN VERS CAMÉRA", "SANS COMPTE"], howKicker: "FONCTIONNEMENT", howTitle: "Trois étapes, sans fil", howBody: "QRBeam lance un lecteur local sur l’ordinateur. Chaque image est vérifiée et le téléphone restaure le fichier après réception.", steps: [["Installez le CLI", "Choisissez Python ou Node.js et installez en une commande."], ["Affichez le fichier", "Lancez qrbeam send FILE pour ouvrir le QR animé."], ["Scannez avec l’iPhone", "QRBeam reçoit, vérifie, enregistre et permet le partage."]], installKicker: "INSTALLATION RAPIDE", installTitle: "Choisissez votre environnement", installBody: "Les versions Python et Node.js utilisent le même protocole QRB1 et offrent la même réception.", installLink: "Guide d’installation complet", comment1: "# Nécessite Python 3.10+", comment2: "# Envoyer un fichier", status: "Le lecteur local s’ouvre sur 127.0.0.1", trustKicker: "CONFIDENTIEL PAR CONCEPTION", trustTitle: "Votre fichier ne fait aucun détour.", trustBody: "Les fichiers et QR restent sur vos appareils. Aucun compte, aucun téléversement de fichier sélectionné, aucun suivi publicitaire.", trustLink: "Lire la politique de confidentialité", supportKicker: "BESOIN D’AIDE ?", supportTitle: "Un blocage ? Résolvons-le ensemble.", supportButton: "Assistance technique" },
    install: { eyebrow: "INSTALLATION", title: "Deux environnements. Une expérience simple.", description: "Choisissez l’environnement déjà présent. Les deux paquets officiels génèrent le même flux QRB1.", pyReq: "Python 3.10 ou version ultérieure", nodeReq: "Node.js 20 ou version ultérieure", recommended: "Recommandé", install: "Installer QRBeam", globalInstall: "Installer QRBeam globalement", send: "Envoyer un fichier", pypi: "Voir sur PyPI", npm: "Voir sur npm", usage: "Premier transfert", usageBody: "Le lecteur local s’ouvre dans le navigateur. Orientez la caméra arrière de l’iPhone vers l’écran.", steps: [["Choisissez un fichier", "Taille maximale : 5 Mio."], ["Lancez la commande", "qrbeam send FILE"], ["Gardez l’image nette", "Plein écran, forte luminosité et téléphone stable."], ["Attendez la vérification", "SHA-256 vérifie le fichier à la fin."]], options: "Options courantes", optionText: ["Mode 6 ips par défaut, adapté au scan à main levée", "10 ips pour un téléphone fixe et un écran lumineux", "Changer le port du lecteur local", "Ne pas ouvrir automatiquement le navigateur"] },
    privacy: { eyebrow: "CONFIDENTIALITÉ", title: "La confidentialité est la valeur par défaut.", description: "Le transfert se déroule devant vous et reste sur vos appareils. Dernière mise à jour : 9 août 2026.", summary: "En bref", bullets: ["Aucun compte", "Aucun fichier sélectionné téléversé", "Aucun contenu QR collecté", "Aucune publicité ni suivi inter-apps"], sections: [["Champ d’application", "Cette politique couvre l’app iOS QRBeam, les CLI Python et Node.js et ce site. Les services externes peuvent appliquer leur propre politique."], ["Fichiers et QR", "Les fichiers sont traités localement. Le lecteur écoute uniquement sur 127.0.0.1 et ne téléverse rien vers un serveur QRBeam. Le récepteur vérifie CRC32 et SHA-256."], ["Caméra", "La caméra sert uniquement à scanner les QR animés. Les images ne sont ni téléversées ni utilisées pour l’identification, la publicité ou l’analyse."], ["Données locales", "L’app peut conserver sur l’appareil les quotas gratuits, réglages et statut d’abonnement. Un fichier reçu n’est écrit que si vous l’enregistrez ou le partagez."], ["Abonnements", "Apple StoreKit gère achats et restaurations. QRBeam lit seulement l’état nécessaire aux avantages et ne reçoit pas les coordonnées bancaires complètes."], ["Données du site", "Ce site ne propose ni compte, ni publicité, ni analyse comportementale, ni cookie marketing. L’hébergeur peut traiter des données de requête standard pour la sécurité et la fiabilité."], ["Limite de sécurité", "QRBeam vérifie l’intégrité, mais le protocole actuel n’offre pas de chiffrement de bout en bout. Ne transférez que les fichiers que vous êtes autorisé à traiter."], ["Contact", "Pour toute question, écrivez à lsl8315@163.com. La date de mise à jour sera modifiée en cas d’évolution."]] },
    support: { eyebrow: "ASSISTANCE", title: "Confiez-nous le problème. Gardez votre fichier.", description: "Essayez d’abord ces solutions courantes. Si le problème persiste, contactez-nous par e-mail.", email: "Assistance par e-mail", emailHint: "Pour les comptes, abonnements ou questions privées", selfHelp: "Aide autonome", faqTitle: "Questions fréquentes", faqHint: "Installation, ports et scan", faqIntro: "Le transfert est hors ligne, mais l’installation initiale du paquet nécessite Internet.", faqs: [["Commande qrbeam introuvable", "Rouvrez le terminal. Vérifiez avec python3 -m pip show qrbeam ou npm list --global qrbeam."], ["Le navigateur ne s’ouvre pas", "Ouvrez l’adresse locale affichée, généralement http://127.0.0.1:8765."], ["Port déjà utilisé", "Choisissez un autre port, par exemple qrbeam send FILE --port 8766."], ["Scan lent ou instable", "Utilisez safe, le plein écran et une forte luminosité, évitez les reflets et stabilisez le téléphone."], ["Le transfert ne se termine pas", "Le flux boucle pour récupérer les images manquantes. Gardez l’app au premier plan et rapprochez le téléphone si nécessaire."], ["Impossible d’envoyer le fichier", "Vérifiez son existence et sa taille maximale de 5 Mio. La formule gratuite peut être limitée à 1 Mio et un transfert par jour."]], report: "Accélérer le diagnostic", reportBody: "Ajoutez les informations suivantes. N’envoyez pas le fichier lui-même sans autorisation de partage.", reportItems: ["Version de QRBeam (qrbeam --version)", "Système et version Python / Node.js", "Modèle d’iPhone et version d’iOS", "Message d’erreur complet ou étapes"] },
  },
  de: {
    common: { install: "Installieren", privacy: "Datenschutz", support: "Support", start: "Loslegen", product: "Produkt", help: "Hilfe", legal: "Rechtliches", installGuide: "Installationsanleitung", how: "Funktionsweise", techSupport: "Technischer Support", contact: "Kontakt", privacyPolicy: "Datenschutzerklärung", footer: "Lokale Dateiübertragung vom Bildschirm zur Kamera.", footerNote: "Für Dateien, die in Ihrer Nähe bleiben sollen.", language: "Sprache" },
    home: { eyebrow: "BILDSCHIRM ZUR KAMERA · OHNE CLOUD", h1: "Dateien springen", h2: "vom Bildschirm aufs Handy.", lede: "QRBeam verwandelt kleine Dateien in animierte QR-Codes. Der Computer zeigt sie an, das iPhone scannt sie – ohne Konto, Kabel oder Cloud.", learn: "So funktioniert es", facts: ["Keine Datei-Uploads", "CRC32- + SHA-256-Prüfung", "Bis zu 5 MiB"], ticker: ["OFFLINE ZUERST", "NUR LOKAL", "GEPRÜFTE ÜBERTRAGUNG", "BILDSCHIRM ZUR KAMERA", "OHNE KONTO"], howKicker: "SO FUNKTIONIERT ES", howTitle: "In drei Schritten übertragen", howBody: "QRBeam startet lokal einen Player. Jeder Frame enthält Prüfdaten; das Telefon stellt die Datei erst nach dem Empfang wieder her.", steps: [["CLI installieren", "Python oder Node.js wählen und mit einem Befehl installieren."], ["Datei abspielen", "qrbeam send FILE ausführen und den animierten QR-Code öffnen."], ["Mit iPhone scannen", "QRBeam empfängt, prüft, speichert und teilt die Datei."]], installKicker: "SCHNELL INSTALLIERT", installTitle: "Vertraute Umgebung wählen", installBody: "Python und Node.js nutzen dasselbe QRB1-Protokoll und bieten denselben Empfang.", installLink: "Vollständige Anleitung", comment1: "# Benötigt Python 3.10+", comment2: "# Datei senden", status: "Der lokale Player öffnet sich auf 127.0.0.1", trustKicker: "DATENSCHUTZ IM DESIGN", trustTitle: "Ihre Datei nimmt keinen Umweg.", trustBody: "Dateien und QR-Frames bleiben auf Ihren Geräten. Kein Konto, kein Upload ausgewählter Dateien, kein Werbe-Tracking.", trustLink: "Datenschutzerklärung lesen", supportKicker: "HILFE BENÖTIGT?", supportTitle: "Festgefahren? Wir lösen es gemeinsam.", supportButton: "Technischen Support öffnen" },
    install: { eyebrow: "INSTALLATION", title: "Zwei Laufzeiten. Ein einfaches Erlebnis.", description: "Wählen Sie die vorhandene Umgebung. Beide offiziellen Pakete erzeugen denselben QRB1-Stream.", pyReq: "Python 3.10 oder neuer", nodeReq: "Node.js 20 oder neuer", recommended: "Empfohlen", install: "QRBeam installieren", globalInstall: "QRBeam global installieren", send: "Datei senden", pypi: "Paket auf PyPI", npm: "Paket auf npm", usage: "Erste Übertragung", usageBody: "Der lokale Player öffnet sich im Browser. Richten Sie die iPhone-Rückkamera auf den Bildschirm.", steps: [["Datei auswählen", "Maximal 5 MiB."], ["Befehl ausführen", "qrbeam send FILE"], ["Bild klar halten", "Vollbild, hohe Helligkeit und ein ruhiges Telefon."], ["Prüfung abwarten", "SHA-256 prüft die fertige Datei."]], options: "Häufige Optionen", optionText: ["Standard: 6 fps für Scannen aus der Hand", "10 fps für ein festes Telefon und helles Display", "Lokalen Player-Port ändern", "Browser nicht automatisch öffnen"] },
    privacy: { eyebrow: "DATENSCHUTZ", title: "Datenschutz ist die Voreinstellung.", description: "Die Übertragung geschieht vor Ihnen und bleibt auf Ihren Geräten. Zuletzt aktualisiert: 9. August 2026.", summary: "Kurz gesagt", bullets: ["Kein Konto", "Keine Uploads ausgewählter Dateien", "Keine Sammlung von QR-Inhalten", "Keine Werbung oder App-übergreifendes Tracking"], sections: [["Geltungsbereich", "Diese Erklärung gilt für die QRBeam-iOS-App, Python- und Node.js-CLI sowie diese Website. Externe Dienste können eigene Richtlinien anwenden."], ["Dateien und QR-Codes", "Dateien werden lokal verarbeitet. Der Sender läuft nur auf 127.0.0.1 und lädt nichts auf QRBeam-Server hoch. Der Empfänger prüft CRC32 und SHA-256."], ["Kamera", "Die Kamera dient ausschließlich zum Scannen animierter QR-Codes. Bilder werden nicht hochgeladen und nicht für Identifikation, Werbung oder Analysen genutzt."], ["Lokale Daten", "Kostenlose Sendekontingente, Einstellungen und Mitgliedsstatus können lokal gespeichert werden. Empfangene Dateien werden nur beim Speichern oder Teilen geschrieben."], ["Abonnements", "Apple StoreKit verarbeitet Käufe und Wiederherstellungen. QRBeam liest nur den erforderlichen Status und erhält keine vollständigen Kartendaten."], ["Website-Daten", "Diese Website hat keine Konten, Werbung, Verhaltensanalyse oder Marketing-Cookies. Der Hosting-Anbieter kann Standard-Anfragedaten für Sicherheit und Zuverlässigkeit verarbeiten."], ["Sicherheitsgrenze", "QRBeam prüft die Integrität, bietet derzeit aber keine Ende-zu-Ende-Verschlüsselung. Übertragen Sie nur Dateien, zu deren Verarbeitung Sie berechtigt sind."], ["Kontakt", "Datenschutzfragen senden Sie an lsl8315@163.com. Bei Änderungen aktualisieren wir das Datum."]] },
    support: { eyebrow: "SUPPORT", title: "Das Problem zu uns. Die Datei zu Ihnen.", description: "Probieren Sie zuerst diese häufigen Lösungen. Falls es weiter hakt, schreiben Sie uns eine E-Mail.", email: "E-Mail-Support", emailHint: "Für Konto-, Abo- oder vertrauliche Fragen", selfHelp: "Selbsthilfe", faqTitle: "Häufige Fragen", faqHint: "Schnelle Hilfe bei Installation, Ports und Scannen", faqIntro: "Die Dateiübertragung ist offline; die erste Paketinstallation benötigt jedoch Internet.", faqs: [["qrbeam-Befehl fehlt", "Terminal neu öffnen. Mit python3 -m pip show qrbeam oder npm list --global qrbeam die Installation prüfen."], ["Browser öffnet sich nicht", "Lokale Adresse aus dem Terminal öffnen, normalerweise http://127.0.0.1:8765."], ["Port ist belegt", "Anderen Port wählen, z. B. qrbeam send FILE --port 8766."], ["Scannen ist langsam oder instabil", "safe-Profil, Vollbild und hohe Helligkeit verwenden, Reflexionen vermeiden und das Telefon ruhig halten."], ["Übertragung endet nicht", "Der Stream wiederholt sich. App im Vordergrund lassen und bei Stillstand den Abstand verkürzen und neu starten."], ["Datei lässt sich nicht senden", "Existenz und Größe bis 5 MiB prüfen. Die Gratisversion kann auf 1 MiB und eine Übertragung pro Tag begrenzt sein."]], report: "Schneller zur Ursache", reportBody: "Fügen Sie diese Angaben bei. Senden Sie die Datei selbst nur, wenn Sie sie teilen dürfen.", reportItems: ["QRBeam-Version (qrbeam --version)", "Betriebssystem und Python-/Node.js-Version", "iPhone-Modell und iOS-Version", "Vollständiger Fehlertext oder Schritte"] },
  },
} as const;
